{% set version = "0.1.0" %}

package:
  name: cgsn_processing
  version: {{ version }}

source:
  url: https://bitbucket.org/ooicgsn/cgsn-processing/get/master.tar.gz
  sha256: ce7863e43fa413ba4ecf588ad65312bd3cfe97324514699d80bf0f939f5e6b8f
  patches:
    - pkg.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gsw >=3.0.3
    - jinja2
    - munch >=2.1.0
    - netcdf4
    - numpy >=1.9.2
    - pandas
    - pyaxiom
    - pytz
    - requests
    - scipy >=0.15.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - cgsn_processing

about:
  home: https://bitbucket.org/ooicgsn/cgsn-processing
  license: MIT
  license_file: LICENSE.txt
  summary: 'processing modules for converting JSON data from the OOI moorings'

extra:
  recipe-maintainers:
    - ocefpaf
