{% set version = "0.2.1" %}

package:
  name: cgsn_processing
  version: {{ version }}

source:
  url: https://github.com/cwingard/cgsn-processing/archive/refs/tags/{{ version }}.tar.gz
  sha256: 79d81d77c8ffd9128dbaf43e709c1867d7767c2590b871c3502a42f2bde8eecb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - gsw
    - h5netcdf
    - jinja2
    - munch
    - netCDF4
    - numpy
    - pandas
    - ppigrf
    - pytz
    - requests
    - scipy
    - xarray

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - cgsn_processing
  commands:
    - pip check

about:
  home: https://github.com/cwingard/cgsn-processing
  license: MIT
  license_file: LICENSE.txt
  summary: 'processing modules for converting JSON data from the OOI moorings'

extra:
  recipe-maintainers:
    - ocefpaf
