travis:
  secure:
    BINSTAR_TOKEN: DjtY6BLzjhUAvI4VHIq//1hix+1g/mKEQncFlEdIe0w+4nxxPNU2dnGwETnG8jJX5le/IxyyA/flT5XmVSu5eicUnr8bLdUwd9+Ejbjx4H1rGgjx+pvKOXkKg5JP+NLyE0PFsk41Cw/AmyWp+qJJsnOm3YEQU8m6LKreo6dUbV4c0OH16Y65+QqlMHXWE862lDEtsXe2Gx5Bg2yNHstRoMvHmjXjjFRwOhBqnQVyYcC7Yz6DglEcVTzNe8DkURvxD9ou+Sgk3CM6+7Jfusmf5YVeirIHPCO7ZtrMrw53AjFpEFkorQAUWCmSxuzQNXz9Xjxt6ZXYQ9YtHb7qCaVLkb2KNnuFyFU36tyhidWIcPuVM2Zki0ShX65PheB3fg7xhMCrJ3acwqnOp9dqhhgtTy62tJKji1acvoVPdUiu1tFO96AkwXWXlO66KfXG8KiKnG5EjuCBitfnVY+ZMg8zDBU3hxgp3zMF1ddgWc0O0ONdNECyF6HOv9tUx4nl4Y8dSguh1zkofFiseMfrzY3MumjpAmOoyjNtm7Hd+gMS9reYuxzjfnbzsitKYmxezhoiD+VXYB4s+9HG0wBdXEE70IWG7GsP6SxCQG9b+N7mu2IypksMiUyQsmYr2YxL64vP2G2T1jyXtCyNFy/nRvbghY0o3v3qPqREvASYDNDrQcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
