travis:
  secure:
    BINSTAR_TOKEN: r30RP6cprWrtBycY2bmcoLk4einf+994fM+YDA44pwKWqo1krGao83oEcmFQ4d0Qxh/iqE2ZoSawYJtkgq5qQWy5COPgCOqJNz9Qjaa0bLC9VdzNSEfPfkaSPGsXHiQic7k7otNZYkENRgBKUOgfpBHjcjnnSdXC/RPEMWzk+njLA2q+3Lg23Aurltwpap/+qAOBRMm0C/3ksyUxi6/xOm1GH/u6Ci1A/vtKuqQWNuvCJZavWEBrHVCl2hxSoa4+Mj/sqTRL/AZv/f/WioRCnSd6mWLLBJ0z4Nc934nvQcu7H+ViSv1kbORYW+sOKLbKIbX4LGLOp9EW9yzHnSeY3ickQtGlS+bDIrRwq5v/YTH6Pift1NPr7dxQi+X8WdUYoBJrUWSQVP0Id+6/l49jZkn866ONQTKX7hOfree9YjPbubeJ+8V14Ozo6IBOrlJABVQq2YoxpQUzoiFyDXn4YPDZrRsxm6CzGX+zd5extp3jKD/WQDfLg5NFiq/CsTBX4iJ+Bc/Sy4zF420QZIdEHQkEfzvVEMoaR8YczFbFtV+tq0i8ku9sz8Yl4CuNRrgxtPKv5GSugO2TMHOz8X1xqhj2nLtG2DJXgF2QcZjA/uThkIIRjyIUy9fGDOKKBmDo/rqkAMXmuXXQ5cXCPEnMD3Btzrc8+Dny6XGBa5dZc4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
